"""
Universal Document Standard (UDS) Helper Functions

Provides functions to generate YAML frontmatter headers/footers for workorder
documentation with metadata tracking, lifecycle management, and traceability.

Part of: WO-UDS-INTEGRATION-001
"""

from datetime import datetime, timedelta
from pathlib import Path
from typing import Optional
import re


def get_server_version() -> str:
    """
    Get the coderef-workflow server version.

    Returns:
        str: Version string in format 'coderef-workflow vX.Y.Z' or 'unknown' if not found

    Acceptance Criteria:
        - Reads version from server.py or constants.py
        - Returns string in format 'coderef-workflow vX.Y.Z'
        - Handles errors gracefully (fallback to 'unknown')
    """
    try:
        # Try reading from server.py first
        server_py = Path(__file__).parent / 'server.py'
        if server_py.exists():
            content = server_py.read_text(encoding='utf-8')
            # Look for version pattern like __version__ = "3.1.1" or VERSION = "3.1.1"
            version_match = re.search(r'(?:__version__|VERSION)\s*=\s*["\']([0-9]+\.[0-9]+\.[0-9]+)["\']', content)
            if version_match:
                return f"coderef-workflow v{version_match.group(1)}"

        # Try constants.py as fallback
        constants_py = Path(__file__).parent / 'constants.py'
        if constants_py.exists():
            content = constants_py.read_text(encoding='utf-8')
            version_match = re.search(r'(?:__version__|VERSION)\s*=\s*["\']([0-9]+\.[0-9]+\.[0-9]+)["\']', content)
            if version_match:
                return f"coderef-workflow v{version_match.group(1)}"

        # Fallback if version not found
        return "coderef-workflow v1.7.0"  # Current version as fallback

    except Exception:
        return "unknown"


def generate_uds_header(
    title: str,
    workorder_id: str,
    feature_name: str,
    status: str = "DRAFT",
    doc_version: str = "1.0"
) -> str:
    """
    Generate UDS YAML header with metadata.

    Args:
        title: Document title (e.g., "Implementation Plan", "Context")
        workorder_id: Workorder ID (e.g., "WO-UDS-INTEGRATION-001")
        feature_name: Feature name (e.g., "uds-integration")
        status: Document status (DRAFT/IN_REVIEW/APPROVED/ARCHIVED)
        doc_version: Document version (default: "1.0")

    Returns:
        str: Valid YAML frontmatter string with --- delimiters

    Acceptance Criteria:
        - Function accepts: title, workorder_id, feature_name, status parameters
        - Returns valid YAML string with --- delimiters
        - Uses ISO 8601 timestamps
        - Includes server version from get_server_version()
    """
    timestamp = datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ")
    server_version = get_server_version()

    header = f"""---
title: {title}
version: {doc_version}
generated_by: {server_version}
workorder_id: {workorder_id}
feature_id: {feature_name}
status: {status}
timestamp: {timestamp}
---"""

    return header


def generate_uds_footer(
    workorder_id: str,
    feature_name: str,
    status: str = "DRAFT",
    review_days: int = 30
) -> str:
    """
    Generate UDS YAML footer with lifecycle metadata.

    Args:
        workorder_id: Workorder ID (e.g., "WO-UDS-INTEGRATION-001")
        feature_name: Feature name (e.g., "uds-integration")
        status: Document status (DRAFT/IN_REVIEW/APPROVED/ARCHIVED)
        review_days: Days until next review (default: 30)

    Returns:
        str: Valid YAML frontmatter string

    Acceptance Criteria:
        - Function accepts: workorder_id, feature_name, status, review_days parameters
        - Calculates next_review as today + review_days (default 30)
        - Returns valid YAML string
        - Includes AI assistance flag (always true for agent-generated docs)
    """
    server_version = get_server_version()
    update_date = datetime.utcnow().strftime("%Y-%m-%d")
    review_date = (datetime.utcnow() + timedelta(days=review_days)).strftime("%Y-%m-%d")

    footer = f"""---
Generated by: {server_version}
Workorder: {workorder_id}
Feature: {feature_name}
Last Updated: {update_date}
AI Assistance: true
Status: {status}
Next Review: {review_date}
---"""

    return footer
