"""
Workorder Document Validator

Validates workorder docs (plan.json, DELIVERABLES.md, context.json, analysis.json, instructions.json)
generated by coderef-workflow against workorder-doc-frontmatter-schema.json
"""

from pathlib import Path
from typing import Optional
from .base import BaseUDSValidator
from ..validator import ValidationError, ValidationSeverity


class WorkorderDocValidator(BaseUDSValidator):
    """Validates workorder documentation generated by coderef-workflow"""

    schema_name = "workorder-doc-frontmatter-schema.json"
    doc_category = "workorder"

    # Common workorder document sections (recommended but not required)
    WORKORDER_SECTIONS = [
        "Executive Summary",
        "Current State",
        "Proposed Changes",
        "Implementation Plan",
        "Testing Strategy",
        "Success Criteria"
    ]

    def validate_specific(self, frontmatter: dict, content: str, file_path: Optional[Path] = None) -> tuple[list[ValidationError], list[str]]:
        """Workorder-specific validation"""
        errors = []
        warnings = []

        # Check workorder sections (recommended)
        missing_sections = self._check_workorder_sections(content)
        if missing_sections:
            warnings.append(f"Missing recommended workorder sections: {', '.join(missing_sections)}")

        # Check doc_type matches filename if file_path provided
        if file_path:
            expected_type = self._infer_doc_type_from_filename(file_path)
            actual_type = frontmatter.get('doc_type')

            if expected_type and actual_type and expected_type != actual_type:
                errors.append(ValidationError(
                    severity=ValidationSeverity.MAJOR,
                    message=f"doc_type '{actual_type}' doesn't match filename (expected '{expected_type}')",
                    field="doc_type"
                ))

        # Warn if status is draft (should be in_progress or complete for execution)
        status = frontmatter.get('status')
        if status == 'draft':
            warnings.append("Workorder status is 'draft' (should be 'in_progress' or 'complete' when executing)")

        return (errors, warnings)

    def _check_workorder_sections(self, content: str) -> list[str]:
        """Check if recommended workorder sections are present"""
        missing = []

        for section in self.WORKORDER_SECTIONS:
            # Look for markdown headers with section name
            if f"## {section}" not in content and f"# {section}" not in content:
                missing.append(section)

        return missing

    def _infer_doc_type_from_filename(self, file_path: Path) -> Optional[str]:
        """Infer doc_type from filename"""
        filename = file_path.name.upper()

        if filename == "PLAN.JSON":
            return "plan"
        elif filename == "DELIVERABLES.MD":
            return "deliverables"
        elif filename == "CONTEXT.JSON":
            return "context"
        elif filename == "ANALYSIS.JSON":
            return "analysis"
        elif filename == "INSTRUCTIONS.JSON":
            return "instructions"

        return None
