"""
Universal Documentation Standards (UDS) - Headers and Footers

Provides UDSHeader and UDSFooter classes for workorder tracking,
MCP attribution, and complete documentation traceability.
"""

from dataclasses import dataclass, asdict
from datetime import datetime
from enum import Enum
from typing import Optional
import yaml


class DocumentType(Enum):
    """CodeRef-specific document types"""
    PLAN = "plan"
    DELIVERABLES = "deliverables"
    ARCHITECTURE = "architecture"
    README = "readme"
    API = "api"
    CHANGELOG = "changelog"


class DocumentStatus(Enum):
    """Document lifecycle status"""
    DRAFT = "DRAFT"
    REVIEW = "REVIEW"
    APPROVED = "APPROVED"
    DEPRECATED = "DEPRECATED"


@dataclass
class UDSHeader:
    """
    UDS Header - YAML frontmatter for complete traceability

    Every CodeRef document must have a UDS header linking it to:
    - The workorder that created it (workorder_id)
    - The MCP server that generated it (generated_by)
    - The feature being implemented (feature_id)
    - Creation/update timestamps
    """

    # Required fields - MUST be present for UDS compliance
    workorder_id: str  # Format: WO-{FEATURE}-{CATEGORY}-###
    generated_by: str  # Format: coderef-{server} v{version}
    feature_id: str    # Feature name (alphanumeric, hyphens, underscores)
    timestamp: str     # ISO 8601 format (YYYY-MM-DDTHH:MM:SSZ)

    # Optional fields
    title: Optional[str] = None
    version: Optional[str] = None
    status: Optional[DocumentStatus] = None
    classification: Optional[str] = None  # INTERNAL, PUBLIC, CONFIDENTIAL
    doc_type: Optional[DocumentType] = None

    def to_yaml(self) -> str:
        """
        Generate YAML frontmatter for document header

        Returns:
            str: YAML frontmatter with --- delimiters

        Example:
            ---
            workorder_id: WO-AUTH-SYSTEM-001
            generated_by: coderef-docs v1.2.0
            feature_id: auth-system
            timestamp: 2025-12-29T10:15:00Z
            title: Authentication System Architecture
            version: 2.1.0
            status: APPROVED
            classification: INTERNAL
            doc_type: architecture
            ---
        """
        data = {}

        # Required fields
        data["workorder_id"] = self.workorder_id
        data["generated_by"] = self.generated_by
        data["feature_id"] = self.feature_id
        data["timestamp"] = self.timestamp

        # Optional fields (only include if set)
        if self.title:
            data["title"] = self.title
        if self.version:
            data["version"] = self.version
        if self.status:
            data["status"] = self.status.value
        if self.classification:
            data["classification"] = self.classification
        if self.doc_type:
            data["doc_type"] = self.doc_type.value

        yaml_content = yaml.dump(data, default_flow_style=False, sort_keys=False)
        return f"---\n{yaml_content}---\n"

    @classmethod
    def from_dict(cls, data: dict) -> "UDSHeader":
        """Create UDSHeader from dictionary"""
        # Convert status string to enum
        if "status" in data and isinstance(data["status"], str):
            data["status"] = DocumentStatus(data["status"])

        # Convert doc_type string to enum
        if "doc_type" in data and isinstance(data["doc_type"], str):
            data["doc_type"] = DocumentType(data["doc_type"])

        return cls(**data)


@dataclass
class UDSFooter:
    """
    UDS Footer - YAML footer for attribution and tracking

    Provides additional metadata about document generation,
    workorder reference, and AI assistance attribution.
    """

    # Required fields
    copyright_year: int
    organization: str
    generated_by: str
    workorder_id: str
    feature_id: str
    last_updated: str  # YYYY-MM-DD format

    # Optional fields
    ai_assistance: bool = True
    status: Optional[DocumentStatus] = None
    next_review: Optional[str] = None  # YYYY-MM-DD format
    contributors: Optional[list[str]] = None

    def to_yaml(self) -> str:
        """
        Generate YAML footer for document

        Returns:
            str: YAML footer with --- delimiters

        Example:
            ---
            Copyright © 2025 | CodeRef Ecosystem
            Generated by: coderef-docs v1.2.0
            Workorder: WO-AUTH-SYSTEM-001
            Feature: auth-system
            Last Updated: 2025-12-29
            AI Assistance: true
            Status: APPROVED
            Next Review: 2026-01-29
            Contributors:
              - Agent1
              - Agent2
            ---
        """
        lines = []
        lines.append(f"Copyright © {self.copyright_year} | {self.organization}")
        lines.append(f"Generated by: {self.generated_by}")
        lines.append(f"Workorder: {self.workorder_id}")
        lines.append(f"Feature: {self.feature_id}")
        lines.append(f"Last Updated: {self.last_updated}")
        lines.append(f"AI Assistance: {str(self.ai_assistance).lower()}")

        if self.status:
            lines.append(f"Status: {self.status.value}")

        if self.next_review:
            lines.append(f"Next Review: {self.next_review}")

        if self.contributors:
            lines.append("Contributors:")
            for contributor in self.contributors:
                lines.append(f"  - {contributor}")

        footer_content = "\n".join(lines)
        return f"---\n{footer_content}\n---\n"

    @classmethod
    def from_dict(cls, data: dict) -> "UDSFooter":
        """Create UDSFooter from dictionary"""
        # Convert status string to enum
        if "status" in data and isinstance(data["status"], str):
            data["status"] = DocumentStatus(data["status"])

        return cls(**data)


def create_uds_header(
    workorder_id: str,
    generated_by: str,
    feature_id: str,
    title: Optional[str] = None,
    version: Optional[str] = None,
    status: DocumentStatus = DocumentStatus.DRAFT,
    doc_type: Optional[DocumentType] = None
) -> UDSHeader:
    """
    Convenience function to create UDS header with auto-generated timestamp

    Args:
        workorder_id: Workorder ID (WO-{FEATURE}-{CATEGORY}-###)
        generated_by: MCP server attribution (coderef-{server} v{version})
        feature_id: Feature name
        title: Optional document title
        version: Optional document version
        status: Document status (default: DRAFT)
        doc_type: Document type

    Returns:
        UDSHeader: Configured header with current timestamp
    """
    return UDSHeader(
        workorder_id=workorder_id,
        generated_by=generated_by,
        feature_id=feature_id,
        timestamp=datetime.utcnow().isoformat() + "Z",
        title=title,
        version=version,
        status=status,
        doc_type=doc_type
    )


def create_uds_footer(
    workorder_id: str,
    generated_by: str,
    feature_id: str,
    organization: str = "CodeRef Ecosystem",
    status: Optional[DocumentStatus] = None,
    contributors: Optional[list[str]] = None
) -> UDSFooter:
    """
    Convenience function to create UDS footer with auto-generated dates

    Args:
        workorder_id: Workorder ID
        generated_by: MCP server attribution
        feature_id: Feature name
        organization: Organization name (default: CodeRef Ecosystem)
        status: Document status
        contributors: List of contributors

    Returns:
        UDSFooter: Configured footer with current dates
    """
    today = datetime.utcnow().date()
    next_review = datetime(today.year + 1, today.month, today.day).date()

    return UDSFooter(
        copyright_year=today.year,
        organization=organization,
        generated_by=generated_by,
        workorder_id=workorder_id,
        feature_id=feature_id,
        last_updated=today.isoformat(),
        status=status,
        next_review=next_review.isoformat(),
        contributors=contributors
    )
