"""
Unit tests for UDS headers and footers
"""

import pytest
from datetime import datetime

from papertrail.uds import (
    UDSHeader,
    UDSFooter,
    DocumentType,
    DocumentStatus,
    create_uds_header,
    create_uds_footer
)


class TestUDSHeader:
    """Test UDS header generation"""

    def test_create_uds_header_minimal(self):
        """Test creating header with minimal fields"""
        header = UDSHeader(
            workorder_id="WO-TEST-FEATURE-001",
            generated_by="coderef-docs v1.0.0",
            feature_id="test-feature",
            timestamp="2025-12-29T10:00:00Z"
        )

        assert header.workorder_id == "WO-TEST-FEATURE-001"
        assert header.generated_by == "coderef-docs v1.0.0"
        assert header.feature_id == "test-feature"
        assert header.timestamp == "2025-12-29T10:00:00Z"

    def test_create_uds_header_full(self):
        """Test creating header with all fields"""
        header = UDSHeader(
            workorder_id="WO-AUTH-SYSTEM-001",
            generated_by="coderef-docs v1.2.0",
            feature_id="auth-system",
            timestamp="2025-12-29T10:15:00Z",
            title="Authentication System",
            version="2.1.0",
            status=DocumentStatus.APPROVED,
            classification="INTERNAL",
            doc_type=DocumentType.ARCHITECTURE
        )

        assert header.title == "Authentication System"
        assert header.version == "2.1.0"
        assert header.status == DocumentStatus.APPROVED
        assert header.classification == "INTERNAL"
        assert header.doc_type == DocumentType.ARCHITECTURE

    def test_to_yaml_minimal(self):
        """Test YAML generation with minimal fields"""
        header = UDSHeader(
            workorder_id="WO-TEST-001",
            generated_by="coderef-docs v1.0.0",
            feature_id="test",
            timestamp="2025-12-29T10:00:00Z"
        )

        yaml_output = header.to_yaml()

        assert yaml_output.startswith("---\n")
        assert yaml_output.endswith("---\n")
        assert "workorder_id: WO-TEST-001" in yaml_output
        assert "generated_by: coderef-docs v1.0.0" in yaml_output
        assert "feature_id: test" in yaml_output
        assert "timestamp: '2025-12-29T10:00:00Z'" in yaml_output

    def test_to_yaml_full(self):
        """Test YAML generation with all fields"""
        header = UDSHeader(
            workorder_id="WO-TEST-001",
            generated_by="coderef-docs v1.0.0",
            feature_id="test",
            timestamp="2025-12-29T10:00:00Z",
            title="Test Doc",
            version="1.0.0",
            status=DocumentStatus.DRAFT,
            doc_type=DocumentType.README
        )

        yaml_output = header.to_yaml()

        assert "title: Test Doc" in yaml_output
        assert "version: 1.0.0" in yaml_output
        assert "status: DRAFT" in yaml_output
        assert "doc_type: readme" in yaml_output

    def test_create_uds_header_convenience(self):
        """Test convenience function creates header with timestamp"""
        header = create_uds_header(
            workorder_id="WO-TEST-001",
            generated_by="coderef-docs v1.0.0",
            feature_id="test"
        )

        assert header.workorder_id == "WO-TEST-001"
        assert header.timestamp is not None
        assert header.timestamp.endswith("Z")  # ISO 8601 with Z suffix


class TestUDSFooter:
    """Test UDS footer generation"""

    def test_create_uds_footer_minimal(self):
        """Test creating footer with minimal fields"""
        footer = UDSFooter(
            copyright_year=2025,
            organization="CodeRef Ecosystem",
            generated_by="coderef-docs v1.0.0",
            workorder_id="WO-TEST-001",
            feature_id="test",
            last_updated="2025-12-29"
        )

        assert footer.copyright_year == 2025
        assert footer.organization == "CodeRef Ecosystem"
        assert footer.workorder_id == "WO-TEST-001"

    def test_to_yaml_minimal(self):
        """Test YAML footer generation with minimal fields"""
        footer = UDSFooter(
            copyright_year=2025,
            organization="CodeRef",
            generated_by="coderef-docs v1.0.0",
            workorder_id="WO-TEST-001",
            feature_id="test",
            last_updated="2025-12-29"
        )

        yaml_output = footer.to_yaml()

        assert yaml_output.startswith("---\n")
        assert yaml_output.endswith("---\n")
        assert "Copyright © 2025 | CodeRef" in yaml_output
        assert "Generated by: coderef-docs v1.0.0" in yaml_output
        assert "Workorder: WO-TEST-001" in yaml_output
        assert "Feature: test" in yaml_output
        assert "Last Updated: 2025-12-29" in yaml_output
        assert "AI Assistance: true" in yaml_output

    def test_to_yaml_with_contributors(self):
        """Test YAML footer with contributors"""
        footer = UDSFooter(
            copyright_year=2025,
            organization="CodeRef",
            generated_by="coderef-docs v1.0.0",
            workorder_id="WO-TEST-001",
            feature_id="test",
            last_updated="2025-12-29",
            contributors=["Agent1", "Agent2", "Human"]
        )

        yaml_output = footer.to_yaml()

        assert "Contributors:" in yaml_output
        assert "  - Agent1" in yaml_output
        assert "  - Agent2" in yaml_output
        assert "  - Human" in yaml_output

    def test_create_uds_footer_convenience(self):
        """Test convenience function creates footer with auto dates"""
        footer = create_uds_footer(
            workorder_id="WO-TEST-001",
            generated_by="coderef-docs v1.0.0",
            feature_id="test"
        )

        assert footer.workorder_id == "WO-TEST-001"
        assert footer.last_updated is not None
        assert footer.next_review is not None
        # Next review should be ~1 year from now
        assert footer.copyright_year == datetime.utcnow().year


class TestDocumentEnums:
    """Test document type and status enums"""

    def test_document_types(self):
        """Test all document types are defined"""
        assert DocumentType.PLAN.value == "plan"
        assert DocumentType.DELIVERABLES.value == "deliverables"
        assert DocumentType.ARCHITECTURE.value == "architecture"
        assert DocumentType.README.value == "readme"
        assert DocumentType.API.value == "api"

    def test_document_statuses(self):
        """Test all document statuses are defined"""
        assert DocumentStatus.DRAFT.value == "DRAFT"
        assert DocumentStatus.REVIEW.value == "REVIEW"
        assert DocumentStatus.APPROVED.value == "APPROVED"
        assert DocumentStatus.DEPRECATED.value == "DEPRECATED"
